[workspace]
resolver = "2"
members = [
    "service",
    "load-test",
    "functional-test",
    "configloader",
]

[workspace.package]
authors = ["Simon <simon.forster98@gmail.com"]

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1