name: "rust-app"

services:

  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    environment:
      - ENVIRONMENT=docker
    ports:
      - "8080:8080"
    env_file: "./api_keys/rust-app.env"
