version: '3.9'
name: "rust-app"

services:

  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    environment:
      - ENVIRONMENT=docker
    ports:
      - "8080:8080"
    networks:
      - local-monitoring

  stub:
    build: stub/.
    ports:
    - "8081:8080"

networks:
  local-monitoring:
    external: true