version: '3.9'
name: "rust-app"

services:

  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    #env_file: "./api_keys/rust-app.env"
    environment:
      - ENVIRONMENT=docker_stubbed
      - RA_NOTION_DB_ID=fakeDb
      - RA_NOTION_CLIENT_KEY=fakeKey
    ports:
      - "8080:8080"
    networks:
      - local-monitoring

  stub:
    build: stub/.
    ports:
    - "8081:8080"

networks:
  local-monitoring:
    external: true