name: "rust-app"

services:

  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    environment:
      - ENVIRONMENT=docker_stubbed
    ports:
      - "8080:8080"

  stub:
    build: stub/.
    ports:
    - "8081:8080"
