version: '3.9'
name: "rust-app"

services:

  service:
    build: service/.
    image: localhost/service:latest
    ports:
      - "8080:8080"

  stub:
    build: stub/.
    ports:
      - "8081:8080"

