logging:
  log-level: info
  pattern: "{d} {l} - {m}{n}"

server:
  port: 8080

notion:
  client:
    url: "https://api.notion.com/"
    notion-version: "2022-06-28"
    key: ""
  db:
    path: "v1/databases/"
    id: ""
