logging:
  log-level: info
  pattern: "{d} {l} - {m}{n}"

server:
  port: 8080

notion:
  client:
    url: "https://api.notion.com/"
    notion-version: "2022-06-28"
    api-key: ""
  db:
    path: "v1/databases/"
    database-id: "abde80ee3af649d58fdbd238c3b6a01b"
